### ISSUE TITLE
is this repo still active?

### ISSUE THREAD

**Issue by jdambly-ns** [ligato/vpp-base#28]
I'm getting the following error

```
dpdk                 [notice]: virtio_init_queue(): virtqueue does not exist
dpdk                 [notice]: eth_virtio_pci_init(): Failed to init virtio device
```

not sure how to fix this, does anyone have more explicit instructions?

**Comment by ondrej-fabry** [comment]
Yes, this repo is still active, but this repo is only for managing docker images for the VPP. It installs pre-built Deb packages downloaded from official FD.io account on packagecloud.

So, this is not really the right place to ask for help with errors you have encountered. However, you can try asking on [vpp-dev mailing list](https://lists.fd.io/g/vpp-dev) or other FD.io community channels.
