### ISSUE TITLE
Using virtio-user interfaces

### ISSUE THREAD

**Issue by mojtaba-eshghie** [ligato/vpp-base#3]
Hi guys,
I am trying to run the vpp + dpdk in containers and have the vpp inside container connected to the vpp in host OS via virtio-user interface. I have tested this scenario with DPDK L2forwarding and everything is fine, but as you see even thought the virtio-user interface is defined in startup.conf I cannot see the VirtioUser interface in vppctl's "show int" command. 
This is the startup.conf file of VPP, 

```
unix {
  nodaemon
  log /var/log/vpp/vpp.log
  full-coredump
  cli-listen /run/vpp/cli-server.sock
}

api-trace {
  on
}

dpdk {
  #vdev virtio_user0
  no-pci
  huge-dir /dev/hugepages
  vdev virtio_user0,path=/var/run/usvhost1
  socket-mem 8,0
  #vdev net_vhost0,iface=/etc/vpp/sock.sock

}

plugins {
  path /home/mojtaba/vpp/build-root/build-vpp_debug-native/vpp/lib/vpp_plugins
  #plugin dpdk_plugin.so { disable }
}

cpu {
  main-core 5
}
```

**Comment by ondrej-fabry** [comment]
@mojtaba-eshghie What does `show vhost-user` output?

**Comment by ondrej-fabry** [comment]
This might be relevant: https://wiki.fd.io/view/VPP/Use_VPP_to_connect_VMs_Using_Vhost-User_Interface

**Comment by mojtaba-eshghie** [comment]
None of them show the created virtio interface, 

> 
> 
> @mojtaba-eshghie What does `show vhost-user` output?
> 
> EDIT: or rather `show virtio pci` ?

**Comment by mojtaba-eshghie** [comment]
> 
> 
> This might be relevant: https://wiki.fd.io/view/VPP/Use_VPP_to_connect_VMs_Using_Vhost-User_Interface
> 
> CC @rastislavszabo

I followed this tutorial before, it works and vhost interfaces can be created correctly. However, I need virtio-user interface which apparently should be added with the following line of vpp configuration and does not work:
` no-pci
  vdev virtio_user0,path=/var/run/usvhost1
`

**Comment by ondrej-fabry** [comment]
I recommend writing to VPP devs on FD.io's mailing list.

**Comment by mojtaba-eshghie** [comment]
> 
> 
> I recommend writing to VPP devs on FD.io's mailing list.

I'll give it a try, 
thanks
